### PR TITLE
Tdd setup

### PR DESCRIPTION
**Pull request by Schokomuesl1**
- Just very initial setup as of now. Added both jest and cypress; jest for unit testing, cypress for automated integration testing.
- After the obligatory npm install to get both dependencies to run the jest unit tests: `npm test`
- Cypress: First start the server  `npm start`, after that start cypress `npx cypress open` and run the test in your favourite browser (see here: https://docs.cypress.io/guides/getting-started/writing-your-first-test.html#Add-a-test-file for more info...)

No _real_ tests as of now, especially for cypress we need some smaller reworks to access the relevant dom elements easily (mostly ids and/or classes I guess...)

### CODE REVIEW

**Review by FelixWohlfrom — APPROVED** [review]
:+1: Looks really nice to me.

Maybe you can extend our CONTRIBUTING.md with a small chapter regarding the tests? Maybe some documentation for jest or how to run them?

**Comment by AntonyGarand** [comment]
Hey!  
Is this PR stale, are you still working on it?  
If not, I'll close the PR so someone else can take the issue!

**Comment by Schokomuesl1** [comment]
Hey Anthony,

sorry, absolutely stale, life caught up a bit just as I was starting...

Maybe I'll try again at a later point but right now: no chance :-(

Cheers,

Daniel

Am Sa., 21. Nov. 2020 um 04:48 Uhr schrieb Antony Garand <
notifications@github.com>:

**Comment by AntonyGarand** [comment]
Alright! Thanks for the info
I'll closes the PR and remove you from the issue, feel free to take another task whenever you have more free time 😁

**Pull request closed without merging**
