### PR TITLE
Adding Docker dev/build instructions

### LINKED ISSUE #9: GitHub Actions / Checks
- NPM:
  - [x] clean install
  - [x] build
  - [x] test
- [x] ~~pushing to master: update site branch with built react~~
- [x] Prettier, eslint checks
- [x] Docker

@mozi-h sturgelose

### PR DESCRIPTION
**Pull request by adamgoose**
This contributes to #9. I'm willing to configure the GitHub Actions for building and pushing to [Docker Hub](https://hub.docker.com/orgs/wintergatan) once I can sync up with @mozi-h to configure secrets on the repository.

### CODE REVIEW

**Comment by mozi-h** [comment]
What would be the benefit of Docker, especially for a relatively non-complex WebApp?
I don't know too much about Docker (the basics), but it seems to me that it really isn't relevant for our plans here and made for simpler, more direct distribution of Services like mail servers or big projects like Nextcloud or WordPress.
This should be just a simple client-run WebApp (and a possible server for handling sharing via link yadda, yadda)

**Comment by adamgoose** [comment]
You're not wrong in that this WebApp is simple, however it's still beneficial to have a containerized build/dev environment, in my opinion. With changes to Node versions and build environments, it provides a consistent environment-as-code. I don't imagine many people will utilize it outside of deploying, which is how I intend to utilize it.

**Comment by mozi-h** [comment]
Is it worth putting the project in yet another container?
So far, to set up you only need to:
1. have Node
2. `npm i`
3. `npm start` or `npm run build`

I don't really see how that's so inconsistent or difficult to justify a whole environment-as-code solution.

Perhaps, if more people see the need (react accordingly), it's an option.

**Comment by adamgoose** [comment]
@phochs and I have worked together to provide cloud infrastructure for the Discord monitoring solution. I imagined this is where the CI environments would live, which is all kubernetes. Docker will be necessary for that. If you don't want it in this repo, it'll wind up in another. :P

**Comment by wraybowling** [comment]
omg no. Docker would over-engineer this thing that should basically be a static single page app. Stop making it more complicated than it needs to be.

**Review by mozi-h — APPROVED** [review]
As discussed on [Discord](https://discordapp.com/channels/649165975647682560/712733531687878676/717837614979481700)

**Pull request merged**
